1st part of project done. testing
Watxesnavo/Book_Store pull request #1
Opened 2023-09-15 21:59 UTC by Watxesnavo

2023-09-23 15:52 UTC, Ivan95kos requested changes
remove this folder and files
<img width="318" alt="Знімок екрана 2023-09-23 о 17 49 24" src="https://github.com/Watxesnavo/Book_Store/assets/41166578/f4d82c83-a3f3-4bbe-a6a6-ad5c9729b58c">

Why you don't have this folder from the first task?
<img width="290" alt="Знімок екрана 2023-09-23 о 17 50 45" src="https://github.com/Watxesnavo/Book_Store/assets/41166578/67017732-88e1-4a23-a722-1e2a5ae18ef6">

2023-09-23 15:52 UTC, Ivan95kos commented on src/main/java/org/store/structure/dto/BookSearchParametersDto.java
> +public record BookSearchParametersDto(String[] authors,
Why don't you use a List or a Set?

2023-09-23 21:40 UTC, Watxesnavo commented on src/main/java/org/store/structure/dto/BookSearchParametersDto.java
> +public record BookSearchParametersDto(String[] authors,
@Ivan95kos because I did it same way as I saw it in the platform video where is explained how to do all the criteria search

2023-09-24 16:39 UTC, Ivan95kos approved these changes
Nice

2023-09-25 18:17 UTC, merged