Testing tests
Watxesnavo/Book_Store pull request #11
Opened 2023-12-04 20:42 UTC by Watxesnavo

2023-12-25 10:52 UTC, Watxesnavo commented
<img width="587" alt="Снимок экрана 2023-12-25 в 11 49 46" src="https://github.com/Watxesnavo/Book_Store/assets/112902418/c86ee3c9-004a-4b6b-a981-59311263c7a8">
<img width="564" alt="Снимок экрана 2023-12-25 в 11 47 31" src="https://github.com/Watxesnavo/Book_Store/assets/112902418/29300a5f-9c90-438f-977e-2d9ec0013ed7">
screenshots of test coverage for both PR Book and ShoppingCart logic

2023-12-25 16:56 UTC, olekskov requested changes

2023-12-25 16:56 UTC, olekskov commented on src/main/java/org/store/structure/dto/book/CreateBookRequestDto.java
> +    @NotEmpty
`@NotEmpty' rejects null so no need in '@NotNull' when it's present

2023-12-25 16:56 UTC, olekskov commented on src/main/java/org/store/structure/dto/book/CreateBookRequestDto.java
> +    @NotEmpty
same

2023-12-25 16:56 UTC, olekskov commented on src/main/java/org/store/structure/dto/order/OrderRequestDto.java
>      @NotNull
same

2023-12-25 16:56 UTC, olekskov commented on src/main/java/org/store/structure/dto/order/OrderStatusUpdateDto.java
>      @NotNull
same

2023-12-25 16:56 UTC, olekskov commented on src/main/java/org/store/structure/service/order/OrderServiceImpl.java
> +    private Order saveDefaultOrder(User userDetails) {
User user is more appropriate

2023-12-25 16:56 UTC, olekskov commented on src/main/java/org/store/structure/service/order/OrderServiceImpl.java
> +    private User getCurrentUser(User userDetails) {
same

2023-12-25 16:56 UTC, olekskov commented on src/test/java/org/store/structure/controller/AuthenticationControllerTest.java
> +                        )
extracting content argument to variable will make code more readable

Please recheck similar cases, they are present in most tests

2024-01-03 21:38 UTC, Watxesnavo commented on src/main/java/org/store/structure/service/order/OrderServiceImpl.java
> +    private Order saveDefaultOrder(User userDetails) {
@olekskov 
![alreadywas](https://github.com/Watxesnavo/Book_Store/assets/112902418/c4cf63db-27e5-42cd-bdc0-22727051d226)
it was there already when i pushed it here.

2024-01-05 22:51 UTC, merged