Test
Watxesnavo/Book_Store pull request #4
Opened 2023-09-25 21:53 UTC by Watxesnavo

2023-10-09 14:40 UTC, Rommelua requested changes

2023-10-09 14:40 UTC, Rommelua commented on src/main/java/org/store/structure/controller/AuthenticationController.java
> +    public String setUserRole(@PathVariable Long id) {
Use Transactional on service layer
Better have one endpoint  
`public UserLoginResponseDto updateRoles(@PathVariable Long id, @RequestParam List<RoleName> roles)`

2023-10-09 14:40 UTC, Rommelua commented on src/main/java/org/store/structure/dto/user/UserRegistrationRequestDto.java
> +    @Size(min = 4, max = 50)
```suggestion
```

2023-10-09 14:40 UTC, Rommelua commented on src/main/java/org/store/structure/dto/user/UserRegistrationRequestDto.java
> +    @Size(min = 4, max = 100)
```suggestion
```

2023-10-09 14:40 UTC, Rommelua commented on src/main/java/org/store/structure/controller/BookController.java
>      public BookDto updateBook(@PathVariable Long id, @RequestBody Book newBook) {
use dto - not Book

2023-10-09 14:40 UTC, Rommelua commented on src/main/java/org/store/structure/service/book/BookServiceImpl.java
> +public class BookServiceImpl implements BookService {
why do we have this class in Security task? It should be in the main branch already.

2023-10-09 14:40 UTC, Rommelua commented on src/main/java/org/store/structure/service/book/BookServiceImpl.java
> +    public BookDto updateBook(Long bookId, Book newBook) {
```suggestion
    public BookDto updateBook(Long bookId, CreateBookRequestDto bookDto) {
```

2023-10-09 14:40 UTC, Rommelua commented on src/main/java/org/store/structure/validation/FieldMatchValidator.java
> +        }
Objects.equals?

2023-10-09 20:16 UTC, Watxesnavo commented on src/main/java/org/store/structure/service/book/BookServiceImpl.java
> +public class BookServiceImpl implements BookService {
@Rommelua because I forgot to merge

2023-10-09 20:22 UTC, Watxesnavo commented on src/main/java/org/store/structure/controller/AuthenticationController.java
> +    public String setUserRole(@PathVariable Long id) {
@Rommelua UserLoginResponseDto only can return me a token when Im logging in, why I have to return a token when I'm only adding/changin roles to the user

2023-10-10 14:46 UTC, Ivan95kos approved these changes
There are too many files for this task, don't forget to merge and send only the current task for future review

2023-10-10 23:14 UTC, merged